on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f D_SCIENCE/PYTHON/requirements.txt ]; then pip install -r D_SCIENCE/PYTHON/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8  D_SCIENCE/PYTHON --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8  D_SCIENCE/PYTHON --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f D_SCIENCE/PYTHON/requirements.txt ]; then pip install -r D_SCIENCE/PYTHON/requirements.txt; fi
    - name: Test with unittest and coverage
      run: |
        coverage run --rcfile=D_SCIENCE/PYTHON/.coveragerc -m unittest discover D_SCIENCE/PYTHON
        coverage report --rcfile=D_SCIENCE/PYTHON/.coveragerc --fail-under=90 -m
